In [8]:
import numpy as np
arr = np.ones((3, 4))

In [ ]:
arr

In [ ]:
arr + 5

In [ ]:
arr*5

In [ ]:
np.empty((3, 4)) # generates very random values

In [ ]:
np.eye(3, dtype = int) #n*n matrix #tO calculate inverse of matroix

In [ ]:
np.eye(3) # always returns a square matrix, here it will be of 3x3

In [ ]:
arr

In [ ]:
#optional

import pandas as pd
pd.DataFrame(arr)

In [ ]:
#extra topics
import random
random.choice((1, 2, 3, 4, 5, 6))

random.choice('Ajay')
random.randrange(1, 10) #Choose a random item from range(start, stop[, step])
random.random() # a random no is generated between o (included), 1 will be excluded

lis = [1, 2, 3, 4, 5]
random.shuffle(lis)

random.uniform(7, 14) # Get a random number in the range [a, b) or [a, b] depending on rounding

In [ ]:
np.array([])

In [ ]:
np.random.random_sample() #Return random floats in the half-open interval [0.0, 1.0)

In [ ]:
type(np.random.random_sample())

In [ ]:
np.random.random_sample((5,)) #Return random floats in the half-open interval [0.0, 1.0).

In [ ]:
np.random.rand(1) # rand(d0, d1, ..., dn) -->Random values in a given shape.

In [ ]:
np.random.rand(2, 3)

In [ ]:
np.random.randn(2, 3) # randn(d0, d1, ..., dn)-->Return a sample (or samples) from the "standard normal" distribution

In [ ]:
np.random.random_sample() #random_sample(size=None)-->Return random floats in the half-open interval [0.0, 1.0).

In [ ]:
np.random.randint(1, 5, size = (3, 4))

In [ ]:
arr = np.random.randint(1, 5, size = (3, 4))

In [ ]:
arr

In [ ]:
arr.size

In [ ]:
arr.shape

In [ ]:
arr.ndim

In [ ]:
arr

In [ ]:
arr.reshape(2, 6) #array size can not change, multiples of array size

In [ ]:
arr.reshape(6, 2)

In [ ]:
arr.reshape(12,)

In [ ]:
arr.reshape(12, 1)

In [ ]:
arr.reshape(12,2)

In [ ]:
arr.reshape(4, 3)

In [ ]:
arr.reshape(3,4)

In [ ]:
arr

In [ ]:
arr.reshape(4, -1) # If you're reshaping an array and you only know the number of rows to put, then put -1 in column. numpy will automatically takecare of it and vice versa

In [ ]:
arr.reshape(4, -100)

In [ ]:
arr.reshape(3, -100)

In [ ]:
arr.reshape(-1, 4) # same here put the number of column uk, and -1 in rows. numpy will automatically decides the number of rows

In [ ]:
arr

In [ ]:
arr.reshape(12, ).base # .reshape is doing shawllow copy, hence .base will return the original array(hence it is pointing to the same memory)

In [ ]:
arr

In [ ]:
arr.size

In [ ]:
arr.reshape(2, 2, 3) # will generate 2 sets of 2x3 array, in-some it'll be an 3-d array

In [ ]:
arr.reshape(1, 2, 2, 3) # will generate 4-d array of 2x3 dimentions

In [ ]:
arr.reshape(4, 3, 1) # will create a 4-d array of 3x1 dimention

In [ ]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

In [ ]:
lis = [1, 2, 3, 4]
arr = np.array(lis)

In [ ]:
arr

In [ ]:
arr.ndim

In [ ]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

In [ ]:
arr2.ndim

In [ ]:
arr2 = np.zeros((3, 4))
arr2

In [ ]:
arr2.ndim

In [ ]:
arr3 = np.zeros((1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d
arr3

In [ ]:
arr3.ndim

In [ ]:
arr3.shape

In [ ]:
arr4 = np.zeros((1, 1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d +1d
arr4

In [ ]:
arr4.ndim

In [ ]:
arr4.shape

In [ ]:
arr3 = np.zeros((3, 3, 4))
arr3

In [ ]:
arr3.ndim

In [ ]:
arr3.shape

In [9]:
arr1 = np.random.randint(1, 10, (5, 6)) # randint(low, high=None, size=None, dtype=int)-->Return random integers from `low` (inclusive) to `high` (exclusive).

In [10]:
arr1

array([[1, 9, 8, 4, 2, 8],
       [2, 8, 8, 3, 5, 5],
       [9, 2, 8, 7, 5, 6],
       [2, 1, 5, 6, 7, 5],
       [4, 6, 5, 4, 3, 7]])

In [13]:
arr1 > 5 # will be true wherever the digit is greater than 5, or else it will be false

array([[False,  True,  True, False, False,  True],
       [False,  True,  True, False, False, False],
       [ True, False,  True,  True, False,  True],
       [False, False, False,  True,  True, False],
       [False,  True, False, False, False,  True]])

In [14]:
arr1[arr1 > 5] # will return the values greater than 5.

array([9, 8, 8, 8, 8, 9, 8, 7, 6, 6, 7, 6, 7])

In [ ]:
arr1[arr1 < 5]

In [ ]:
arr1

In [ ]:
arr

In [ ]:
arr[0]

In [ ]:
arr[0]

In [12]:
arr1

array([[1, 9, 8, 4, 2, 8],
       [2, 8, 8, 3, 5, 5],
       [9, 2, 8, 7, 5, 6],
       [2, 1, 5, 6, 7, 5],
       [4, 6, 5, 4, 3, 7]])

In [11]:
arr1[0, [1,3]] # from 0th row return element of index 1,3, use comma to select a sepecific element of a specific column and row

array([9, 4])

In [16]:
arr1[2:4, [2,3]] # will return elements from 2nd to 4rth row(exclusive 4rth row), 2nd element column and 3rd element column(inclusive 3rd element in 3rd column)

array([[8, 7],
       [5, 6]])

In [17]:
arr1[0:2, [0,2]] #0th - 1st row in continuation and 0th and 2nd column

array([[1, 8],
       [2, 8]])

In [ ]:
#slicing on both rows and column
arr1[0:2, 1:3] # 2nd row and 3rd column will be exclusive

In [ ]:
arr1[0:2, [0, 1]]

In [ ]:
arr

In [ ]:
arr1[0, [1,3]]

In [ ]:
arr1[2:4, [0, 2]]

In [ ]:
arr1

In [19]:
arr1[2:5] # slicing

array([[9, 2, 8, 7, 5, 6],
       [2, 1, 5, 6, 7, 5],
       [4, 6, 5, 4, 3, 7]])

In [ ]:
arr1[2:5, 0:2] #slicing

In [ ]:
arr1[2:5, [0, 2]]

In [18]:
arr1[[2,4]] #selecting specific column

array([[9, 2, 8, 7, 5, 6],
       [4, 6, 5, 4, 3, 7]])

In [20]:
arr1

array([[1, 9, 8, 4, 2, 8],
       [2, 8, 8, 3, 5, 5],
       [9, 2, 8, 7, 5, 6],
       [2, 1, 5, 6, 7, 5],
       [4, 6, 5, 4, 3, 7]])

In [ ]:
arr1

In [ ]:
arr1[[2, 4]] #selecting specific column

In [ ]:
arr1[2 : 4] #slicing

In [ ]:
arr1

In [ ]:
arr1[2:4, [1, 3]]

In [22]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [23]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

##

In [24]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [25]:
arr1 + arr2

array([[3, 3, 4],
       [4, 4, 3],
       [2, 3, 2]])

In [26]:
arr1 - arr2

array([[ 1,  1,  0],
       [ 0,  0,  1],
       [ 0, -1,  0]])

In [27]:
arr1 * arr2

array([[2, 2, 4],
       [4, 4, 2],
       [1, 2, 1]])

In [ ]:
#matrix multiplication


arr1

In [ ]:
arr2

In [ ]:
# suppose you're multiplying (mxn) matrix with (pxq), only multiply if n==p and the resulting materix will be in the dimension of m and q, or else multiplication will not happen.

In [28]:
arr1 @ arr2 # matrix multiplication

array([[ 8, 10,  8],
       [ 8, 10,  8],
       [ 4,  5,  4]])

In [30]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [31]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [29]:
arr1 / arr2 #index wise divison

array([[2. , 2. , 1. ],
       [1. , 1. , 2. ],
       [1. , 0.5, 1. ]])

In [ ]:
arr1

In [32]:
arr1 / 0 # numpy understand infinity but python does-not

<ipython-input-32-f39b50d43667>:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Broad casting

In [33]:
arr = np.zeros((3, 4))

In [34]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [36]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
a = np.array([1, 2, 3, 4])

In [38]:
a.shape

(4,)

In [39]:
a

array([1, 2, 3, 4])

In [40]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [41]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
a

array([1, 2, 3, 4])

In [43]:
a = np.array([1, 2, 3])

In [44]:
a = np.array([[1, 2, 3]])

In [45]:
a.T

array([[1],
       [2],
       [3]])

In [46]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a

array([[1, 2, 3]])

In [48]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [ ]:
a.T

In [ ]:
a = np.array([1, 2, 3])
a.T

In [49]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [50]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.        ]])

In [51]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.     , 0.     ]])

In [52]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 2.71828183]])

In [53]:
a

array([[1, 2, 3]])

In [54]:
np.min(a)

1

In [55]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [56]:
np.min(arr1)

1

In [57]:
np.max(arr1)

2

In [ ]:
arr1

In [58]:
arr1.T

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [59]:
arr1.flatten() #reduce higher dimension to 1 d

array([2, 2, 2, 2, 2, 2, 1, 1, 1])

In [ ]:
#expand_dims >>  expands the array by inserting a new axis

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [64]:
np.sum(arr)

27

In [65]:
np.sum(arr, axis = 0) # sum row wise, tho it seems column wise

array([ 6,  9, 12])

In [66]:
np.sum(arr, axis = 1) # sum column wise, tho it seems row wise

array([ 6, 15,  6])

In [67]:
#expand_dims >>expand the dimension of array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [68]:
arr.ndim

1

In [69]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [70]:
arr1.ndim

2

In [71]:
arr2 = np.expand_dims(arr1, axis = 0) # increses the dimention of passed array by 1
arr2

array([[[1, 2, 3, 4]]])

In [72]:
arr2.shape

(1, 1, 4)

In [73]:
arr

array([1, 2, 3, 4])

In [74]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [79]:
arr = np.zeros((3, 4))

In [76]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr1 = np.expand_dims(arr, axis = 1) # column wise dinesion has incresed by 1
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [78]:
arr1 = np.expand_dims(arr, axis = 0) #row wise the dimension has increased by 1
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])