In [ ]:
import numpy as np
data = np.array([[1], [2], [3]])

In [ ]:
data.ndim

2

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
a=np.squeeze(data) # will reduce an array by one dimension

In [ ]:
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
#repeat
data

array([[1],
       [2],
       [3]])

In [ ]:
np.repeat(data, 4) # Repeat elements of an array.

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.repeat(a, 2) # we can observe that it gives output after flattening the array, no dimension, original shape

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.repeat(a, 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [ ]:
np.repeat(a, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(data, -2)

array([[3],
       [1],
       [2]])

In [ ]:
np.diag(np.array([1, 2, 3, 4])) #np.diag(v, k=0)-->Extract a diagonal or construct a diagonal array.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
a = np.array([[[1, 2], [3, 4], [5,6]]])

In [ ]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
np.roll(a, 2, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
#binary operation on array

In [ ]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [ ]:
arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [ ]:
arr2

array([[3, 9, 6, 7],
       [2, 7, 4, 7],
       [9, 3, 6, 3]])

In [ ]:
arr1+arr2

array([[ 5, 16,  7, 13],
       [ 6, 14,  8,  9],
       [16, 12, 14,  7]])

In [ ]:
arr1*arr2 # index vise multiplication

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [ ]:
arr1 / arr2

array([[0.66666667, 0.77777778, 0.16666667, 0.85714286],
       [2.        , 1.        , 1.        , 0.28571429],
       [0.77777778, 3.        , 1.33333333, 1.33333333]])

In [ ]:
arr1 - arr2

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [ ]:
arr1 ** arr2

array([[       8, 40353607,        1,   279936],
       [      16,   823543,      256,      128],
       [40353607,      729,   262144,       64]])

In [ ]:
arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [ ]:
arr2

array([[3, 9, 6, 7],
       [2, 7, 4, 7],
       [9, 3, 6, 3]])

In [ ]:
arr1 > arr2

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
~arr1 # bit-wise negation of arr1

array([[ -3,  -8,  -2,  -7],
       [ -5,  -8,  -5,  -3],
       [ -8, -10,  -9,  -5]])

In [ ]:
arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [ ]:
#Numpy string function

In [ ]:
arr = np.array(["pw", "skills"])

In [ ]:
arr

array(['pw', 'skills'], dtype='<U6')

In [ ]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [ ]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [ ]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
#Mathematical function


arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [ ]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.84147098, -0.2794155 ],
       [-0.7568025 ,  0.6569866 , -0.7568025 ,  0.90929743],
       [ 0.6569866 ,  0.41211849,  0.98935825, -0.7568025 ]])

In [ ]:
np.cos(arr1)

array([[-0.41614684,  0.75390225,  0.54030231,  0.96017029],
       [-0.65364362,  0.75390225, -0.65364362, -0.41614684],
       [ 0.75390225, -0.91113026, -0.14550003, -0.65364362]])

In [ ]:
np.tan(arr1)

array([[-2.18503986,  0.87144798,  1.55740772, -0.29100619],
       [ 1.15782128,  0.87144798,  1.15782128, -2.18503986],
       [ 0.87144798, -0.45231566, -6.79971146,  1.15782128]])

In [ ]:
np.log10(arr1)

array([[0.30103   , 0.84509804, 0.        , 0.77815125],
       [0.60205999, 0.84509804, 0.60205999, 0.30103   ],
       [0.84509804, 0.95424251, 0.90308999, 0.60205999]])

In [ ]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 2.71828183e+00, 4.03428793e+02],
       [5.45981500e+01, 1.09663316e+03, 5.45981500e+01, 7.38905610e+00],
       [1.09663316e+03, 8.10308393e+03, 2.98095799e+03, 5.45981500e+01]])

In [ ]:
np.power(arr1, 3)

array([[  8, 343,   1, 216],
       [ 64, 343,  64,   8],
       [343, 729, 512,  64]], dtype=int32)

In [ ]:
np.mean(arr1)

5.083333333333333

In [ ]:
np.max(arr1)

9

In [ ]:
np.std(arr1) # Compute the standard deviation along the specified axis.

2.4986107250941583

In [ ]:
np.var(arr1) # Compute the variance along the specified axis.

6.243055555555556

In [ ]:
np.max(arr1)

9

In [ ]:
arr1 - arr2

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [ ]:
np.subtract(arr1, arr2)

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [ ]:
arr1 * arr2

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [ ]:
np.multiply(arr1, arr2)

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [ ]:
np.mod(arr1, arr2) #return element wise remainder

array([[2, 7, 1, 6],
       [0, 0, 0, 2],
       [7, 0, 2, 1]])

In [ ]:
np.power(arr1, arr2)

array([[       8, 40353607,        1,   279936],
       [      16,   823543,      256,      128],
       [40353607,      729,   262144,       64]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 2.64575131, 1.        , 2.44948974],
       [2.        , 2.64575131, 2.        , 1.41421356],
       [2.64575131, 3.        , 2.82842712, 2.        ]])

In [ ]:
#sort search

In [ ]:
arr = np.array([5, 6, 1, 2])

In [ ]:
arr

array([5, 6, 1, 2])

In [ ]:
np.sort(arr)

array([1, 2, 5, 6])

In [ ]:
arr = np.array([5, 6,100, 200, 1, 2, 8, 9])

In [ ]:
# a = np.sort(arr)

In [ ]:
arr

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [ ]:
np.sort(arr)

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [ ]:
np.searchsorted(arr, 3)

6

In [ ]:
np.searchsorted(arr, 3)

4

In [ ]:
arr1 = np.array([0, 1, 2, 3, 0, 4])
np.count_nonzero(arr1)

4

In [ ]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [ ]:
arr1

array([0, 1, 2, 3, 0, 4])

In [ ]:
np.where(arr1 > 0) # will return index at which arr1>0

(array([1, 2, 3, 5], dtype=int64),)

In [ ]:
np.extract(arr1 > 0, arr1) # will return data which greater than 0

array([1, 2, 3, 4])

In [ ]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [ ]:
#matrix >> 2d array

In [ ]:
import numpy.matlib as nm """numpy.matlib(matrix library) is a submodule of the NumPy library that provides functions for creating matrices and matrix-related operations.
                               It offers functionalities similar to the MATLAB programming language,
                                particularly for matrix manipulation and linear algebra operations."""

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#Numpy linear algebra

In [ ]:
arr1

array([0, 1, 2, 3, 0, 4])

In [ ]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [ ]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [ ]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [ ]:
a  = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [ ]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [ ]:
b = np.array([16, -8, 0])

In [ ]:
b

array([16, -8,  0])

In [ ]:
np.linalg.solve(a, b) # solving linear algebric equations to find value of x y and z

array([0.90162081, 2.89483603, 1.88465888])

In [ ]:
arr1

array([[2, 3],
       [4, 5]])

In [ ]:
5*2 - 3*4

-2

In [ ]:
np.linalg.det(arr1) # determinant of an array

-2.0

In [ ]:
np.linalg.inv(arr1) # inverse of an array (Formula: A*A^-1 = I) where A^-1 = A/ determinant of A

array([[-2.5,  1.5],
       [ 2. , -1. ]])